### PR TITLE
Fix for g_getplayervieworigin crash

### PR DESCRIPTION
**Pull request by efinst0rm**
Fix for ERROR: G_GetPlayerViewOrigin(): Couldn't find "tag_player" on player's view-link parent.
Problem is that the helicopter gets deleted, but the final killcam tries to use it.
Credit goes to @ineedbots

### CODE REVIEW

**Comment by Laupetin** [comment]
This can no longer be merged since the controller support PR introduced the vanilla _helicopter.gsc with fixes to the controls.
Could you maybe put these changes in the current existing _helicopter.gsc so this can be merged?

As far as i can see changes were made at lines (your version):
```
393
1372-1387
2061-2070
```

**Comment by efinst0rm** [comment]
Should be good to go.

**Review by Laupetin — APPROVED** [review]
Tested it, didn't run into issues.

**Comment by Laupetin** [comment]
Thanks for the contribution :)

**Pull request merged**
