### PR TITLE
iw4x_russian.str

### PR DESCRIPTION
**Pull request by K-Faktor**
Added Russian localization

### CODE REVIEW

**Comment by Dss0** [comment]
all the Cyrillic letters in your file were replaced with �, possibly caused by the charset you used.

**Comment by K-Faktor** [comment]
no problems. this is how github displays
Снимок экрана 2022-07-18 082544

**Comment by diamante0018** [comment]
Desktop Screenshot 2022 07 18 - 17 02 12 47
I do not speak Russian nor I can read it, but is it fair to assume this is not readable cyrillic?

**Comment by K-Faktor** [comment]
It's simple, it's your English client of the game does not recognize the Cyrillic alphabet
IW4x_ Multiplayer 20 07 2022 10_45_16
IW4x_ Multiplayer 20 07 2022 10_45_22
IW4x_ Multiplayer 20 07 2022 10_45_46
Modern Warfare 2 Multiplayer 20 07 2022 10_44_48

**Comment by diamante0018** [comment]
Can you send us the files for that as well?

**Comment by K-Faktor** [comment]
> Can you send us the files for that as well? So that my client can recognize the russian fonts too?

You just need to use the Russian Steam game client

**Comment by diamante0018** [comment]
We cannot merge this as it is not useful for people that do now have the Russian Steam game client.
We would like to expand the languages IW4x supports but we need all the relevant files to allow a client to switch languages.
iw4x_russian.str is just one file. We also need the rest, like the fonts for the Russian characters.

**Pull request closed without merging**
