### PR TITLE
Make server info look slightly better.

### PR DESCRIPTION
**Pull request by 4doorsmorehoes**
Before: 
image
After:
iw4x_2022-08-22_13-28-52

If anybody doesn't like the changes just yeet this pr lol

### CODE REVIEW

**Comment by Dss0** [comment]
im not sure this is better man, definitely not worse tho. maybe move the items on the right side all the way to the map image and also move the security level so it lines up with the end of the map image.

**Comment by diamante0018** [comment]
Before looks cooler imo

**Comment by 4doorsmorehoes** [comment]
image

**Comment by diamante0018** [comment]
idk I'm not a designer, don't really know.
Before, it looks 'cooler' because it has a black background with stripes at the end.
Afte,r looks a bit dull.

**Pull request closed without merging**
